"""Rule Generator UI - AI-Powered Validation Rule Generation"""

import streamlit as st
import pandas as pd
import logging

logger = logging.getLogger(__name__)


def _generate_rules_with_comprehensive_engine(file_path, sheet_name, header_row, df):
    """Generate rules using the comprehensive engine with deep Excel scanning"""
    from features.rule_generator.engine import (
        deep_scan_rule_sheet,
        extract_comprehensive_metadata,
        generate_comprehensive_ai_prompt,
        post_process_rules
    )
    from features.profiling.ui import AzureOpenAIConfig
    import json
    import time
    from openai import AzureOpenAI
    
    # Initialize Azure OpenAI client
    client = AzureOpenAI(
        api_version=AzureOpenAIConfig.AZURE_OPENAI_API_VERSION,
        azure_endpoint=AzureOpenAIConfig.AZURE_OPENAI_ENDPOINT,
        api_key=AzureOpenAIConfig.AZURE_OPENAI_KEY
    )
    
    # Step 1: Deep scan Excel sheet for rules (if Excel file)
    column_rules = {}
    if file_path and sheet_name and (file_path.endswith('.xlsx') or file_path.endswith('.xls')):
        logger.info(f"Deep scanning sheet '{sheet_name}' with header row {header_row}")
        column_rules = deep_scan_rule_sheet(file_path, sheet_name, header_row)
        logger.info(f"Found rules for {len(column_rules)} columns")
    
    # Step 2: Process each column
    all_rules = []
    total_cols = len(df.columns)
    
    progress_bar = st.progress(0)
    status_text = st.empty()
    
    for idx, column_name in enumerate(df.columns):
        try:
            status_text.text(f"Processing column {idx + 1}/{total_cols}: {column_name}")
            progress_bar.progress((idx + 1) / total_cols)
            
            # Get rule text from deep scan
            rule_text = column_rules.get(column_name, None)
            rule_source = "Rules from Existing Sheet" if rule_text else "Generated by AI"
            
            # Extract metadata from column name and rule text
            metadata = extract_comprehensive_metadata(column_name, rule_text)
            
            # Get sample data
            sample_data = df[column_name].dropna().astype(str).head(100).tolist()
            data_type = str(df[column_name].dtype)
            null_pct = (df[column_name].isnull().sum() / len(df)) * 100
            unique_pct = (df[column_name].nunique() / len(df)) * 100
            
            # Generate AI prompt
            prompt = generate_comprehensive_ai_prompt(
                column_name=column_name,
                sample_data=sample_data,
                data_type=data_type,
                null_pct=null_pct,
                unique_pct=unique_pct,
                metadata=metadata,
                rule_source=rule_source
            )
            
            # Call Azure OpenAI
            response = client.chat.completions.create(
                model=AzureOpenAIConfig.AZURE_OPENAI_DEPLOYMENT,
                messages=[
                    {"role": "system", "content": "You are a data quality expert. Return only valid JSON."},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.3,
                max_tokens=1500
            )
            
            # Parse response
            response_text = response.choices[0].message.content.strip()
            
            # Remove markdown code blocks if present
            if response_text.startswith('```'):
                response_text = response_text.split('```')[1]
                if response_text.startswith('json'):
                    response_text = response_text[4:]
                response_text = response_text.strip()
            
            result = json.loads(response_text)
            
            # Extract rules from response
            if 'rules' in result:
                # Post-process rules to ensure correct dimension mapping and formatting
                processed_rules = post_process_rules(result['rules'], metadata)
                
                for rule_idx, rule in enumerate(processed_rules):
                    all_rules.append({
                        'S.No': len(all_rules) + 1,
                        'Column': column_name,
                        'Business Field': column_name,
                        'Rule Source': rule_source,
                        'Dimension': rule.get('dimension', 'Validity'),
                        'Data Quality Rule': rule.get('data_quality_rule', rule.get('rule_statement', '')),
                        'Issues Found': rule.get('issues_found', 0),
                        'Issues Found Example': rule.get('issues_found_example', '✓ All values valid - No issues found')
                    })
            
            # Rate limiting
            time.sleep(1.0)
            
        except Exception as e:
            logger.error(f"Error processing column '{column_name}': {str(e)}")
            # Add fallback rule
            all_rules.append({
                'S.No': len(all_rules) + 1,
                'Column': column_name,
                'Business Field': column_name,
                'Rule Source': 'Generated by AI',
                'Dimension': 'Validity',
                'Data Quality Rule': f"{column_name} should be validated",
                'Issues Found': 0,
                'Issues Found Example': f"Error: {str(e)}"
            })
    
    progress_bar.empty()
    status_text.empty()
    
    # Create DataFrame
    validation_df = pd.DataFrame(all_rules)
    
    return validation_df


def render_rule_generator():
    """Main Rule Generator interface - Comprehensive engine with Excel sheet scanning"""
    
    
    state = st.session_state.app_state
    df = state.df
    
    # Check if data is loaded
    if df is None:
        st.warning("⚠️ Please load data first before generating rules.")
        st.info("Go to the 'Load Data' tab and upload your file.")
        return
    
    # Check if file is Excel
    file_path = state.file_path
    is_excel = file_path and (file_path.endswith('.xlsx') or file_path.endswith('.xls'))
    
    
    # Use the sheet and header row from loaded data
    if is_excel:
        selected_sheet = state.selected_sheet if hasattr(state, 'selected_sheet') else None
        header_row = state.header_row if hasattr(state, 'header_row') else 0
    else:
        selected_sheet = None
        header_row = state.header_row if hasattr(state, 'header_row') else 0
    
    
    # Import AI components
    try:
        from features.profiling.ui import AzureOpenAIConfig, DynamicValidationDetector
    except ImportError as e:
        st.error(f"Failed to import AI components: {str(e)}")
        return
    
    # Check Azure OpenAI configuration
    missing_config = AzureOpenAIConfig.validate()
    if missing_config:
        st.error(f"⚠️ Azure OpenAI not configured. Missing: {', '.join(missing_config)}")
        st.info("Please set these in your Streamlit secrets (.streamlit/secrets.toml):")
        st.code("""
[default]
AZURE_OPENAI_ENDPOINT = "https://your-resource.openai.azure.com/"
AZURE_OPENAI_KEY = "your-api-key"
AZURE_OPENAI_DEPLOYMENT = "gpt-4o-mini"
AZURE_OPENAI_API_VERSION = "2024-12-01-preview"
AZURE_OPENAI_MAX_RPM = 60
        """)
        return
    
    
    # Generation controls
    col1, col2, col3 = st.columns([2, 2, 2])
    
    with col1:
        if not state.ai_validation_rules_generated:
            if st.button("🚀 Generate AI Validation Rules", type="primary", use_container_width=True):
                with st.spinner("🤖 Analyzing data with comprehensive engine..."):
                    try:
                        # Use comprehensive engine
                        validation_df = _generate_rules_with_comprehensive_engine(
                            file_path, 
                            selected_sheet if is_excel else None,
                            header_row,
                            df
                        )
                        
                        # Store in state for persistence
                        state.ai_validation_rules = validation_df
                        state.ai_validation_rules_generated = True
                        
                        # Explicitly save to disk
                        from state.session import _save_persisted_data
                        _save_persisted_data()
                        
                        st.success(f"✅ Generated {len(validation_df)} validation rules!")
                        st.rerun()
                    except Exception as e:
                        st.error(f"❌ Error generating rules: {str(e)}")
                        logger.error(f"Rule generation failed: {str(e)}", exc_info=True)
        else:
            st.success("✅ Rules Generated")
    
    with col2:
        if state.ai_validation_rules_generated:
            if st.button("🔄 Regenerate Rules", type="secondary", use_container_width=True):
                state.ai_validation_rules_generated = False
                state.ai_validation_rules = pd.DataFrame()
                
                # Explicitly save to disk
                from state.session import _save_persisted_data
                _save_persisted_data()
                st.rerun()
    
    with col3:
        if state.ai_validation_rules_generated:
            if st.button("🗑️ Clear Rules", type="secondary", use_container_width=True):
                state.ai_validation_rules_generated = False
                state.ai_validation_rules = pd.DataFrame()
                
                # Explicitly save to disk
                from state.session import _save_persisted_data
                _save_persisted_data()
                st.success("Rules cleared!")
                st.rerun()
    
    st.divider()
    
    # Display generated rules
    if state.ai_validation_rules_generated and state.ai_validation_rules is not None and not state.ai_validation_rules.empty:
        validation_df = state.ai_validation_rules
        
        # Summary metrics
        col1, col2, col3 = st.columns(3)
        
        with col1:
            st.metric("Total Rules", len(validation_df))
        
        with col2:
            unique_cols = validation_df['Column'].nunique() if 'Column' in validation_df.columns else 0
            st.metric("Columns Covered", unique_cols)
        
        with col3:
            unique_dims = validation_df['Dimension'].nunique() if 'Dimension' in validation_df.columns else 0
            st.metric("DQ Dimensions", unique_dims)
        
        st.divider()
        
        # Display rules table
        st.subheader("📋 Data Quality Rules")
        
        # Display columns - include Rule Source
        display_cols = ['S.No', 'Column', 'Business Field', 'Rule Source', 'Dimension', 'Data Quality Rule', 'Issues Found', 'Issues Found Example']
        display_cols = [c for c in display_cols if c in validation_df.columns]
        
        # Style the dataframe
        def highlight_issues(val):
            if isinstance(val, (int, float)) and val > 0:
                return 'background-color: #fee2e2; color: #991b1b; font-weight: bold;'
            return ''
        
        def highlight_examples(val):
            if isinstance(val, str) and val.startswith('✓'):
                return 'background-color: #dcfce7; color: #166534; font-size: 11px;'
            elif isinstance(val, str) and len(val) > 0:
                return 'background-color: #fef3c7; color: #92400e; font-size: 11px;'
            return ''
        
        def highlight_dimension(val):
            colors = {
                'Accuracy': 'background-color: #dbeafe; color: #1e40af',
                'Completeness': 'background-color: #dcfce7; color: #166534',
                'Consistency': 'background-color: #fef3c7; color: #92400e',
                'Validity': 'background-color: #fce7f3; color: #9d174d',
                'Uniqueness': 'background-color: #f3e8ff; color: #6b21a8',
                'Timeliness': 'background-color: #ccfbf1; color: #0f766e',
                'Integrity': 'background-color: #fee2e2; color: #991b1b',
                'Conformity': 'background-color: #e0e7ff; color: #3730a3',
                'Reliability': 'background-color: #ffedd5; color: #9a3412',
                'Relevance': 'background-color: #ecfccb; color: #3f6212',
                'Precision': 'background-color: #fae8ff; color: #86198f',
                'Accessibility': 'background-color: #e0f2fe; color: #075985',
                'Character Length': 'background-color: #fef3c7; color: #92400e; font-weight: bold;'
            }
            return colors.get(val, '')
        
        def highlight_rule_source(val):
            if val == "Rules from Existing Sheet":
                return 'background-color: #dcfce7; color: #166534; font-weight: bold;'
            elif val == "Generated by AI":
                return 'background-color: #dbeafe; color: #1e40af; font-weight: bold;'
            return ''
        
        # Apply styling and display
        row_count = len(validation_df)
        table_height = min(max(row_count * 35 + 50, 300), 600)
        
        styled_df = validation_df[display_cols].style\
            .applymap(highlight_dimension, subset=['Dimension'])\
            .applymap(highlight_rule_source, subset=['Rule Source'] if 'Rule Source' in display_cols else [])\
            .applymap(highlight_issues, subset=['Issues Found'])\
            .applymap(highlight_examples, subset=['Issues Found Example'])
        
        st.dataframe(styled_df, use_container_width=True, height=table_height)
        
        st.caption(f"Showing {len(validation_df)} rules")
        
        st.divider()
        
        # Export to Excel only
        st.subheader("💾 Export Rules")
        
        try:
            from io import BytesIO
            buffer = BytesIO()
            with pd.ExcelWriter(buffer, engine='openpyxl') as writer:
                validation_df.to_excel(writer, index=False, sheet_name='Data Quality Rule')
            buffer.seek(0)
            
            st.download_button(
                label="📥 Download as Excel",
                data=buffer,
                file_name=f"data_quality_rules_{state.filename}.xlsx",
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                use_container_width=False
            )
        except Exception as e:
            st.error(f"Excel export failed: {str(e)}")
    
    else:
        # No rules generated yet
        st.info("👆 Click 'Generate AI Validation Rules' to start")
        
        st.markdown("""
        ### What will be generated?
        
        The comprehensive AI engine will:
        
        **For Excel Files:**
        - 🔍 Scan selected sheet for existing validation rules
        - 📋 Extract rules from ALL rows (above and below header)
        - 💬 Read cell comments and notes
        - 🔗 Detect merged cells with rule information
        - 📊 Extract metadata patterns (VARCHAR2(360), CHAR(19), NUMBER(10,2), etc.)
        
        **Rule Generation:**
        - ✅ **Rules from Existing Sheet**: Uses detected rules from Excel
        - 🤖 **Generated by AI**: Creates intelligent rules when none found
        
        **Validation Dimensions:**
        - **Validity**: Data type and format validation
        - **Character Length**: Maximum length constraints
        - **Completeness**: Mandatory fields, not null
        - **Uniqueness**: Unique values, no duplicates
        - **Conformity**: Format restrictions, patterns
        - **Accuracy**: Value ranges, precision
        
        ### Output Format:
        
        Columns: S.No | Business Field | Rule Source | Dimension | Data Quality Rule | Issues Found | Issues Found Example
        
        ### Processing Time:
        
        - Approximately 2-3 seconds per column
        - For {0} columns: ~{1:.1f} minutes
        - Progress is shown during generation
        
        ### Features:
        
        ✅ Deep Excel sheet scanning for existing rules
        ✅ Scans ALL rows above and below header
        ✅ Extracts metadata from column names
        ✅ Reads cell comments and notes
        ✅ Generates human-readable rules
        ✅ Validates data against generated rules
        ✅ Provides examples of issues found
        ✅ Clearly marks rule source (Existing vs AI Generated)
        """.format(len(df.columns), len(df.columns) * 2.5 / 60))
